// forum url passthrou
export const FORUM_ADD_FORUM_URL = 'FORUM_ADD_FORUM_URL';
export const FORUM_CLEAR_FORUM_URL = 'FORUM_CLEAR_FORUM_URL';

export const FORUM_AUTH_IN_PROGRESS = 'FORUM_AUTH_IN_PROGRESS';
export const FORUM_AUTH_SUCCESS = 'FORUM_AUTH_SUCCESS';
export const FORUM_AUTH_FAIL = 'FORUM_AUTH_FAIL';
export const FORUM_GENERATE_KEYPAIR_START = 'FORUM_GENERATE_KEYPAIR_START';
export const FORUM_GENERATE_KEYPAIR_SUCCESS = 'FORUM_GENERATE_KEYPAIR_SUCCESS';
export const FORUM_GENERATE_KEYPAIR_FAIL = 'FORUM_GENERATE_KEYPAIR_FAIL';
export const FORUM_GET_FORUM_INFO_IN_PROGRESS = 'FORUM_GET_FORUM_INFO_IN_PROGRESS';
export const FORUM_GET_FORUM_INFO_SUCCESS = 'FORUM_GET_FORUM_INFO_SUCCESS';
export const FORUM_GET_FORUM_INFO_FAIL = 'FORUM_GET_FORUM_INFO_FAIL';